/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ChargeSchema extends BaseModel {
  static $columns = ['amountMinor', 'cancelledAt', 'createdAt', 'currency', 'customerId', 'description', 'dueDate', 'id', 'organizationId', 'paidAt', 'paidMinor', 'recurringPlanId', 'status', 'updatedAt'] as const
  $columns = ChargeSchema.$columns
  @column()
  declare amountMinor: number
  @column.dateTime()
  declare cancelledAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare description: string
  @column.date()
  declare dueDate: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column.dateTime()
  declare paidAt: DateTime | null
  @column()
  declare paidMinor: number
  @column()
  declare recurringPlanId: number | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CustomerSchema extends BaseModel {
  static $columns = ['createdAt', 'displayName', 'financeContactName', 'financeEmail', 'financePhone', 'generalContactName', 'generalEmail', 'generalPhone', 'id', 'kind', 'locale', 'organizationId', 'taxId', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare displayName: string
  @column()
  declare financeContactName: string | null
  @column()
  declare financeEmail: string | null
  @column()
  declare financePhone: string | null
  @column()
  declare generalContactName: string | null
  @column()
  declare generalEmail: string | null
  @column()
  declare generalPhone: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare kind: string
  @column()
  declare locale: string
  @column()
  declare organizationId: number
  @column()
  declare taxId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class InvitationSchema extends BaseModel {
  static $columns = ['acceptedAt', 'createdAt', 'email', 'expiresAt', 'id', 'organizationId', 'role', 'token', 'updatedAt'] as const
  $columns = InvitationSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare role: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MembershipSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'organizationId', 'role', 'updatedAt', 'userId'] as const
  $columns = MembershipSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: number
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['createdAt', 'defaultCurrency', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultCurrency: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = ['amountMinor', 'chargeId', 'createdAt', 'id', 'method', 'organizationId', 'paidOn', 'reference', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column()
  declare amountMinor: number
  @column()
  declare chargeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare method: string
  @column()
  declare organizationId: number
  @column.date()
  declare paidOn: DateTime
  @column()
  declare reference: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RecurringPlanSchema extends BaseModel {
  static $columns = ['active', 'amountMinor', 'createdAt', 'currency', 'customerId', 'description', 'dueDay', 'id', 'nextChargeOn', 'organizationId', 'updatedAt'] as const
  $columns = RecurringPlanSchema.$columns
  @column()
  declare active: boolean
  @column()
  declare amountMinor: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currency: string
  @column()
  declare customerId: number
  @column()
  declare description: string
  @column()
  declare dueDay: number
  @column({ isPrimary: true })
  declare id: number
  @column.date()
  declare nextChargeOn: DateTime
  @column()
  declare organizationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReminderLogSchema extends BaseModel {
  static $columns = ['chargeId', 'createdAt', 'eventKey', 'failureReason', 'id', 'locale', 'organizationId', 'recipientEmail', 'sentAt', 'status', 'updatedAt'] as const
  $columns = ReminderLogSchema.$columns
  @column()
  declare chargeId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventKey: string
  @column()
  declare failureReason: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare locale: string
  @column()
  declare organizationId: number
  @column()
  declare recipientEmail: string
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReminderRuleSchema extends BaseModel {
  static $columns = ['createdAt', 'daysAfter', 'daysBefore', 'enabled', 'id', 'organizationId', 'updatedAt'] as const
  $columns = ReminderRuleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare daysAfter: number
  @column()
  declare daysBefore: number
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare organizationId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isPlatformAdmin', 'locale', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPlatformAdmin: boolean
  @column()
  declare locale: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
